#====================
# DATABASE
#====================

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newcrinity
    username: root
    password: crinity21!

---

spring:
  profiles: dev
port: 9999

---

spring:
  profiles: local
port: 9090

